# Site settings
title: Wales
client:
  name: Wales
  link: "http://www.visitwales.com/"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
description: >
  Croeso i Gymru – willkommen in Wales! 2018 feiert Wales mit dem Jahr des Meeres seine atemberaubende Küste mit ihren hunderten Sandstränden und versteckten Buchten, den kleinen und großen Inseln...

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/wales" # the subpath of your site, e.g. /blog/
img:     "/de/wales/_assets/img"
css:     "/de/wales/_assets/css"
js:      "/de/wales/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed