# Site settings
title: Wales
client:
  name: Visit Wales
  link: http://www.visitwales.com/?utm_source=secret-escapes&utm_medium=email&utm_campaign=yl47
description: >
  Wales is the stuff of legends. Craggy peaks and wild weather, ruined castles clinging to precarious summits, folk tales and new writers – Wales is a landscape of drama, irresistible romance, and superlative escapes.
baseurl: "/wales" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [js/scripts.min.js]
sass:
    sass_dir: css
    style: compressed