# Site settings
title: Wales
client:
  name: Wales
  link: "http://www.visitwales.com/"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Lorem ipsum dolor sit amet

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/wales" # the subpath of your site, e.g. /blog/
img:     "/wales/_assets/img"
css:     "/wales/_assets/css"
js:      "/wales/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed