# Site settings
title: Wales
client:
  name: Visit Wales
  link: http://www.visitwales.com/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Wales is the stuff of legends. Craggy peaks and wild weather, ruined castles clinging to precarious summits, folk tales and new writers – Wales is a landscape of drama, irresistible romance, and superlative escapes.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/wales" # the subpath of your site, e.g. /blog/
img:     "/wales/_assets/img"
css:     "/wales/_assets/css"
js:      "/wales/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed